name: feature_auth
description: Autonomous Authentication feature package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  core_network:
    path: ../core_network
  design_system:
    path: ../design_system
